# Generated by Django 5.2.4 on 2025-08-07 02:31

import startup.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', startup.accounts.managers.UserManager()),
            ],
        ),
    ]
